version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.6.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  fluentd:
    build: fluentd
    ports:
      - 24284:24384
    volumes:
      - ./log:/fluentd/log
      - ./fluentd/fluentd.conf:/fluentd/etc/fluentd.conf
    links:
      - elasticsearch
  kibana:
    image: kibana:7.6.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    links:
      - elasticsearch
